config/routes.rb
Imeko::Application.routes.draw do
  

  get "program", to: "home#program"

  get "call_for_papers", to: "home#cfp"

  get "info", to: "home#info"

  root to: 'home#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def program
  end

  def cfp
  end

  def info
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/application/_chromeframe.html.erb
<%# Prompt IE 6 users to install Chrome Frame. Remove this if you support IE 6. %>
<%# chromium.org/developers/how-tos/chrome-frame-getting-started %>
<!--[if lt IE 7]><p class=chromeframe>Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p><![endif]-->

app/views/application/_footer.html.erb
<footer id="footer">
  <small class="copyright">
    Imeko, Copyright &copy; <%= Date.today.year %>
  </small>
</footer>

app/views/application/_head.html.erb
<head>
  <meta charset="utf-8">

  <%# Use the .htaccess and remove these lines to avoid edge case issues. %>
  <%# More info: h5bp.com/b/378 %>
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <title></title>
  <meta name="description" content="">

  <%# Mobile viewport optimized: h5bp.com/viewport %>
  <meta name="viewport" content="width=device-width">

  <%= render "stylesheets" %>

  <%# More ideas for your <head> here: h5bp.com/d/head-Tips %>

  <%# All JavaScript at the bottom, except polyfills %>
  <%= javascript_include_tag "polyfills" %>

  <%= csrf_meta_tag %>
</head>

app/views/application/_header.html.erb
    <nav id="main-nav">
	<ul>
		<li><%= active_link_to "Imeko 2013", root_path %></li>
		<li><%= active_link_to "Program", program_path %></li>
		<li><%= active_link_to "Registrations", '#' %></li>
		<li><%= active_link_to "Call for Papers", call_for_papers_path %></li>
		<li><%= active_link_to "General Information", info_path %></li>
	</ul>
</nav>

<header id='logo' class="clearfix">
	<figure>
		<%= image_tag('logo.jpg') %>
	</figure>
	<h1 id="logo-text"><a href="index.html" title="">21<sup>TH</sup>IMEKO TC2</a></h1>		
		<p id="intro">Symposium on Photonics in Measurement, Gdansk, 2013</p>

</header>

app/views/home/cfp.html.erb
<h1>Home#cfp</h1>
<p>Find me in app/views/home/cfp.html.erb</p>

app/views/home/index.html.erb
<section class="row-fluid">
<section class="span8">
	<h2><span>IMEKO</span> International Measurement Confederation</h2>
			
				
			IMEKO is a non-governmental federation of 39 Member Organizations individually concerned with the  advancement of measurement technology.
			 Its fundamental objectives are the promotion of international interchange of scientific and technical information in the field of measurement and instrumentation and the enhancement of international cooperation among scientists and engineers from research and industry.

			Founded in 1958, the Confederation has consultative status with
			UNESCO and UNIDO and is one of the five Sister Federations within FIACC:
			Five International Associations Co-ordinating Committee, further consisting of:<br />
<br />
IFAC- International Federation of Automatic Control<br />
IFIP - International Federation for Information Processing<br/>
IFORS - International Federation of Operational Research Societies<br />
IMACS - International Association for Mathematics and Computers in Simulation
			
</section>

<section class="span4">
	sfagdsgdsgdsgdsgsdgdsgsdgsd
	fd sfskjf gksghkjfhgjkdh gdfg jdgd
</section>
</section>

app/views/home/info.html.erb
<h1>Home#info</h1>
<p>Find me in app/views/home/info.html.erb</p>

app/views/home/program.html.erb
<h1>Home#program</h1>
<p>Find me in app/views/home/program.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<%# http://paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither %>
<%= html_tag :class => "no-js", :lang => "en" %>
  <%= render "head" %>

  <body class="pages">
    <%= render "chromeframe" %>
    <%= render "header" %>

    <div id="main" role="main">
      <%= render "flashes" %>
      <%= yield %>
    </div>

    <%= render "footer" %>

    <%# Javascript at the bottom for fast page loading %>
    <%= render "javascripts" %>
  </body>
</html>